version: '3.7'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=itrace
      - POSTGRES_PASSWORD=itrace
      - POSTGRES_DB=itrace
    container_name: itrace_database
